### ISSUE TITLE
Unpauses intentionally paused videos

### ISSUE THREAD

**Issue by robertmaxton42** [lawfx/YoutubeNonStop#1]
First, I'd just like to say thanks for making this extension. It's such a little thing but *oh gods is it obnoxious* to put up with, and I'm very glad I didn't have to write it myself :V.

That said, I do have a minor bug report - if you intentionally pause a video and leave it open for later, when it eventually gets the "Continue watching?" popup, the addon auto-clicks and then unpauses the video, letting it play in the background and probably losing your place. 

It occurs to me that distinguishing between "paused intentionally" and "paused by addon" is somewhat nontrivial -- maybe just keep a record of whether it was paused a few seconds ago, and reset it to that state? I don't think the popup is so annoying as to show up a few seconds after you demonstrate activity, after all... though maybe there's an edge case with playlists. Mm.

**Comment by lawfx** [comment]
Hmm, so the popup pops up even if the video is paused? It never occurred to me, since I generally don't leave tabs that aren't playing music around for that long but I will try to test it today and push a necessary bug fix as soon as possible.

**Comment by lawfx** [comment]
I wasn't able to get the confirmation to pop in a paused video(neither normally nor in a playlist). However, there was indeed a bug that made manually paused videos to start playing after the pc was e.g woken up from hibernation. This might have fixed your problem too. I'll leave this issue open for the time being, so if you encounter it again after the update, let me know. :)

**Comment by lawfx** [comment]
There seems to be no further issue, so I'll close this.
