### ISSUE TITLE
Paused videos start playing

### ISSUE THREAD

**Issue by SimonLammer** [lawfx/YoutubeNonStop#12]
I had two youtube videos paused in seperate tabs and was listening to youtube music in yet another tab. Suddenly the two paused videos started playing.

I suppose this happened because this add-on detected the discontinuation of the music, but hit play on youtube tabs instead of just starting the music.

**Comment by lawfx** [comment]
I'm not sure what might have happened here. I'm using the extension myself pretty much all day when I'm working and stuff, and never had any issue with videos starting randomly. Most likely it was just some random glitch in the matrix. :D

**Comment by Zerwin** [comment]
I had this also happen quite frequently, just having a youtube video tab paused in the background and switching to something else caused it for me after a while.
