### ISSUE TITLE
Media play/pause button doesn't work

### ISSUE THREAD

**Issue by krizajb** [lawfx/YoutubeNonStop#13]
If one presses pause media button the plugin automatically plays the video.

**Comment by lawfx** [comment]
I am aware of this issue. I have tried solving that in the past, I managed to get it working for YouTube but the way you have to detect the event breaks the media keys functionality in every other page that deals with videos. So for the time being, I have no solution for this. Sorry.

**Comment by krizajb** [comment]
Wouldn't it make more sense to leave the issue opened? Care to share that solution or maybe make it accessible on demand via a user configuration?
