### ISSUE TITLE
youtube did something - playlist stuck on 3rd song since tab got unfocused

### ISSUE THREAD

**Issue by ghost** [lawfx/YoutubeNonStop#14]
Seems like youtube did something recently(1-3 days ago at most) whereby listening to music in a playlist(the Uploads playlist of a channel, to be exact, just in case it matters) while the tab isn't focused will get stuck on the 3rd song on repeat instead of advancing to the next song in the playlist, because for some reason it seems that the playlist frame isn't loading/loaded while tab is unfocused.

So workaround is, I guess, just keeping the tab focused.

I've tested this with the NewRetroWave Uploads playlist and ungoogled-Chromium	77.0.3865.114 (Developer Build) (64-bit) with a bunch of extension that used to work before. (**edit:** tested .112 and .90, same thing)
<s>Technically it could be the chromium version change/update, but I doubt it. Previously used *.112 and *.111, *.110, *.106, *.98</s> it's not chromium(see edit)
uBlock Origin development build 1.22.5.1
uBlock Origin Extra 2.86
uMatrix 1.4.0
Sloth 0.1.1
Video Speed Controller 0.5.2.1
YouTube NonStop 0.6.0
HSTS Hacky 0.4.1.0

Ok here some screens on how it looks:
basically, I started(pressed Play) at song name (in playlist) - `Mulperi - Fearless` and then I switched tabs(so that tab got unfocused).
Then I waited until the third song started to repeat itself(instead of playing the 4th song in chain). The 3rd song being: `Futurecop! - Zen 4040`, and then I clicked that tab to focus it and I took these screenshots:
Screenshot_2019-10-08_01-16-47.png
(^ that screenshots and  2 more looked the same, basically and the last one was: Screenshot_2019-10-08_01-17-01.png  ; only important for filename timestamp)
now, because I was compiling in the background it took like 14 sec to load the playlist anew(note: normally this loading wasn't happening before, but youtube changed something! something that makes it not load anything unless the tab is focused!  I doubt chromium changed this, it must've been youtube itself)
and this is the last screenshot:
Screenshot_2019-10-08_01-17-05.png

now attaching them:
Screenshot_2019-10-08_01-16-47.png
![Screenshot_2019-10-08_01-16-47](https://user-images.githubusercontent.com/49106389/66356234-9ceb9200-e96a-11e9-8837-1bd9a653c75e.png)
(yep that's the second song on screen while in this unloaded/unrefreshed state)

Screenshot_2019-10-08_01-17-05.png
![Screenshot_2019-10-08_01-17-05](https://user-images.githubusercontent.com/49106389/66356236-a117af80-e96a-11e9-91e2-3d7247f657bc.png)
(^ here it refreshed itself, I don't press F5 or anything!)

Ok, so to my understanding, because the playlist is white/notloaded like that(in the first screenshot) that's why it keeps repeating the same song. As soon as tab is focused and playlist is refreshing itself/loaded(like in the second screenshot) the next song progresses normally!

Anyway, here's the url to the playlist:
https://www.youtube.com/watch?v=hZDzG4ixXbg&list=UUD-4g5w1h8xQpLaNS_ghU4g&index=19

(notice how, and this was also true before when it was still working, as the playlist progresses you can only see the prior 20 or so songs)

**edit:** I notice the title of the tab is stuck on the second song! (even though it's the third song playing on repeat) - so this is another hint that the issue is present.

**Comment by lawfx** [comment]
I am experiencing the playlist looping as well. But it's not a problem with YouTube NonStop or something that should be fixed by me. It will eventually be fixed by YouTube(I hope...) since they messed up as usual. In case some time passes and YouTube decides that this is a "feature", then I will try addressing it with this extension.

**Comment by lawfx** [comment]
This is not happening to me anymore, I guess YouTube fixed it. I'll leave this open for a couple of days if anyone wants to add anything and then I'm closing it.
