### ISSUE TITLE
Version for FireFox can not work now.

### ISSUE THREAD

**Issue by 7czzl** [lawfx/YoutubeNonStop#15]

**Comment by lawfx** [comment]
I will need more info. From all I know, you may be experiencing problems that are produced by YouTube itself. Lately, YouTube has way more bugs than usual.

**Comment by lawfx** [comment]
Please check the newest version(v0.7.0) and let me know if it works now for you.

**Comment by lawfx** [comment]
No update so I'm considering it fixed.
