### ISSUE TITLE
Stopped working recently due to youtube update

### ISSUE THREAD

**Issue by St0RM53** [lawfx/YoutubeNonStop#17]
Please fix it!

**Comment by thsowers** [comment]
What browser are you using? Chrome extension is currently working fine for me

**Comment by lawfx** [comment]
If you are using Chrome I just released a new update(v0.7.0). For Firefox it will arrive shortly. Test again and let me know.

**Comment by St0RM53** [comment]
firefox

**Comment by lawfx** [comment]
No update so I'm considering it fixed.
