### ISSUE TITLE
Pause/Unpause Conflict With Streamkeys

### ISSUE THREAD

**Issue by camdecoster** [lawfx/YoutubeNonStop#18]
I noticed within the last week or so that Streamkeys (which I use for controlling playback of YouTube videos) was immediately unpausing a video after I just paused it. After some investigation, I figured out that it was YouTube NonStop causing the problem since the issue went away once I disabled that extension. I'm using version 0.7.1 of the extension with Chrome 78.0.3904.87 on Windows 7. What information could I provide to help fix this bug?

**Comment by lawfx** [comment]
Duplicate #22
