### ISSUE TITLE
Add on-off switch on youtube page

### ISSUE THREAD

**Issue by JorricksTU** [lawfx/YoutubeNonStop#2]
Hello,

I would love to see some sort of indication that it picked up the youtube page and that it is working. Now I was thinking, what better way to do this then by an on-off switch. This would also automatically half-fix the other open issue.

Thanks for your work! Saved me a couple of hours doing it myself ;)!

**Comment by lawfx** [comment]
There is an indication that the extension picked up that the tab is a Youtube one, already. The extension's logo icon(located next to the address bar along with other possible extensions) turns red when in Youtube and is grayed out when not. I want to keep the whole extension's activity as unobstructive as possible, kind of like install and forget, so certainly I don't want the user to have to turn it on manually. :)
