### ISSUE TITLE
Playlists stop playing as of recently (Firefox)

### ISSUE THREAD

**Issue by Storm-Engineer** [lawfx/YoutubeNonStop#21]
I don't know when this started as I wasn't listening to playlists for a while, so I only noticed it yesterday, and I also don't know if it's the addon not working or is something else.

Every now and then the playlist will not start playing the next video after moving onto it. When I notice this and open the tab I don't see any popups, just that the next video in the list is loaded but is stopped.

Sometimes it starts playing again if I just mouse over the tab without opening, other times only when I open the tab and mouse over the video, and sometimes only when I actually click on the video.

It also happens if the YouTube tab is the one in focus, but Firefox is not the window in focus.

**Comment by jacekmusial** [comment]
Youtube does have small issue omitting videos that are age restricted, and require user to be logged in. On Google Chrome incognito tab, without any plugins, start this playlist https://youtu.be/MG6xju93jUk?list=PLAY6HGR5-rPMDXTXhEQg4S6YKl40ZKABz&t=356 and it will load next song in a few seconds that is age restricted. In my case, it does show loading bar but do not switch to next video in the public playlist which is not age restricted. 
![image](https://user-images.githubusercontent.com/7474972/72203795-71e07500-3468-11ea-8c6b-6dc5e58073ad.png)
I was wondering if it would be possible to include feature to detect age restricted video and proceed to the next one (for instance by pressing Shift+N). Any thoughts?

I didn't notice any difference of Youtube on minimized/focused tab.

Can you state your operating system (or just User Agent), browser and plugins that are active? And are you logged in to the Youtube and age is set as adult person?

**Comment by ite-klass** [comment]
After I updated to Firefox 72 I had this problem at first, but it quickly started working again without my intervention. It has been working fine for several days for me now.

**Comment by Storm-Engineer** [comment]
I don't think it's age verification related in my case. I guess in theory music videos could be age verified due to swearing, but it always seems to stop on a different video, and the time it takes for it to happen seems kinda consistent.

**Comment by faeriespeck** [comment]
Hello... I found this site when I googled how to solve the "still watching" pop up on YouTube when it is on autoplay... my question is if there is a way to add the addon,  or modified version, through my smart TV?  I also find it necessary to give full transparency... this site is way out of my technical scope and comfort but I'm also excited about the possibility of learning new things and getting that little annoying popup vanquished 🙂

**Comment by Storm-Engineer** [comment]
@faeriespeck Hi! This site (github) is for people to store their programming projects, and this particular part we are in right now is for handling support tickets. You commented on a support ticket I posted about an issue with this project.

This is project is the browser addon "YoutubeNonStop" which can only be used with the Firefox and Chrome browser on a computer. So no smart TVs.

As far as I know there is nothing you can do on a smart TV because, well, it's not a computer and you have no control over it. If you were using a computer instead, then you had a bunch of options, and you could also remove advertisements from every website, including YouTube.

But this conversation does not belong here on this support ticket.

**Comment by Storm-Engineer** [comment]
Though I guess it doesn't matter because this addon seems to be abandoned. No reply to tickets, no updates, nothing for months. :(

**Comment by lawfx** [comment]
Hi @Storm-Engineer, I'm sorry but this addon was created to just counter the specific popup "Video paused. Continue watching?". Other issues that YouTube has(which are plenty) are not part of this project's scope. Sorry to disappoint you.

@faeriespeck If your smart TV has Android OS then you can add the addon and choose to use the Desktop version of youtube(it won't work with m.youtube.com). Previous experiments have shown that it will work like that.

I'm closing this issue since it's irrelevant to this project.

**Comment by Storm-Engineer** [comment]
@lawfx But are you sure my issue described is not related to the "are you watching" popup? Because it is the exact same pattern of stopping playback after a while and then repeating with a certain frequency.
