### ISSUE TITLE
Not working anymore on chrome?

### ISSUE THREAD

**Issue by salad0314** [lawfx/YoutubeNonStop#24]
Hello!!
I think it is not working on my chrome anymore?
The auto stop pop is still popping up and the music stops playing ..

Thanks!! :)

**Comment by lawfx** [comment]
Hi @salad0314 , are you referring to music.youtube.com or youtube.com?

**Comment by 3ph** [comment]
Having same issue on classic youtube.com - the video pauses.

**Comment by afogarty85** [comment]
Same issue; classic youtube.com will pause with addon.

**Comment by salad0314** [comment]
> Hi @salad0314 , are you referring to music.youtube.com or youtube.com?

Sorry for the late reply. 
I mean youtube.com

Does location matters? 
My sister using the same extension and it’s working for her in Canada. I’m in Japan right now so wondering if it matters.. 🧐

**Comment by lawfx** [comment]
I updated the extension guys, check if the problem persists with the new version and let me know.
@salad0314 Location doesn't matter for the extension. Where it could matter, is if YouTube is performing experiments with new features in selected areas that could potentially break the extension in its current form.

**Comment by Storm-Engineer** [comment]
@lawfx Since you never replied to me on my ticket I'm posting this here:

I reported the addon being broken last December, where the popup does not display but the video is still stopped. You closed my ticket and never replied to my question. :(

I'll test 0.8.0 if it fixes it for me too, otherwise I'm going to make a new ticket.

**Comment by salad0314** [comment]
> I updated the extension guys, when the new version(v0.8.0) is published, check if the problem persists and let me know.
> @salad0314 Location doesn't matter for the extension. Where it could matter, is if YouTube is performing experiments with new features in selected areas that could potentially break the extension in its current form.

Halo~ 
Thank you very much! 
I have been using it for 5 days since u updated the extension and it is working very well! 
The window doesn’t pop up and music video keeps playing. 

Thanks for fixing it!! :)

**Comment by lawfx** [comment]
Since no problems reported for some time, I'm closing this. Feel free to open a new issue if problems reappear.
