### ISSUE TITLE
Privacy: Any tracking?

### ISSUE THREAD

**Issue by Echolon** [lawfx/YoutubeNonStop#33]
Hello,

I just wanted to ask if there is any tracking included in that add-on?

Kind regards

**Comment by duiker101** [comment]
I did not make the extension, but looking at the code there doesn't seem to be tracking. You can probably download the extension from the store and check the code there to make sure it's the same but to be 100% sure(might automatically be updated later) I would suggest downloading this code and loading it as an unpacked extension.

**Comment by lawfx** [comment]
There is absolutely no tracking involved. The code is open for checking it and the released versions here are the exact ones that are uploaded to the stores.
