### ISSUE TITLE
Can't pause a video

### ISSUE THREAD

**Issue by JohnyP36** [lawfx/YoutubeNonStop#41]
After multiple times clicking on the "are you there?" (by the extension) it just locks the video. 
This means the following: 
1) the video is playing
2) the play/pause button is on paused
3) I can't pause the video; only after reloading the page or by playing the video picture-in-picture

This problem occurs on youtube.com (I don't know if it also occurs on music.youtube.com
I'm using Edge (Chromium based)

**Comment by zubus** [comment]
Same with Firefox 90.0b12 (64-bit)

**Comment by Mlocik97** [comment]
Same problem,... I'm unable to pause video as well... need to reload website to be able to pause it. I have this problem on YT Music

**Comment by JohnyP36** [comment]
@lawfx Is https://github.com/lawfx/YoutubeNonStop/commit/9fdc16c73a00516465015b6a00a82e649ecd3de7 a fix for this problem?

**Comment by Mlocik97** [comment]
Yes, it's fixed.

**Comment by JohnyP36** [comment]
Then i will close this issue

**Comment by JohnyP36** [comment]
I'm running on MS Edge. If YouTube wants to pause the video in the console there normally comes `blocked attempted to ...`. But sometimes I'll get `video pause requested` but if I get the latest one the play/pause button will be paused and because of the `blocked attempt...` it will still play the video.  
But if I want to manually pause the video inside youtube itself the button wouldn't work (so I have to use the media keys).

**Comment by Mlocik97** [comment]
well now it happens again.

**Comment by dcmbrown** [comment]
I have this problem as well on Firefox 96.0.3.  Just downloaded 0.9.1.
I have this version on Chrome as well with no issues.  Been using this plugin forever there on Chrome.
