### ISSUE TITLE
Youtube Music

### ISSUE THREAD

**Issue by elish77** [lawfx/YoutubeNonStop#5]
Doesn't function with music.youtube.com

**Comment by lawfx** [comment]
Sorry but music.youtube.com is not available in my country so I can't test it and as a result support it for the time being.

**Comment by lawfx** [comment]
v0.5.0 added support for music.youtube.com

**Comment by ThaDaVos** [comment]
I have 0.8.0 of the extension and I am getting the popup again but it looks like music.youtube.com has new UI - maybe it's broken?

PS: Please pm me I am willing to help you if you still cannot access it
