### ISSUE TITLE
Does not have any effect on Firefox on Linux

### ISSUE THREAD

**Issue by VGerris** [lawfx/YoutubeNonStop#50]
Latest version 0.9.1 is activated but does not do anything for youtube.com on Fedora 38 Linux and Firefox 112.0.2 .

**Comment by JohnyP36** [comment]
if you install https://addons.mozilla.org/en-US/firefox/addon/ytnonstop/ does that work?

**Comment by VGerris** [comment]
hi, it does not seem to, but was I wrong to assume the plugin should skip ads? That is what I was looking for.

**Comment by VGerris** [comment]
looks like I did, closing, apologies. I never had the issue of stopped play.
