### ISSUE TITLE
This extention Stopped working

### ISSUE THREAD

**Issue by ReemX** [lawfx/YoutubeNonStop#51]
You cant see the the continue watching window but the video still stops.

**Comment by JohnyP36** [comment]
try https://addons.mozilla.org/nl/firefox/addon/ytnonstop/

**Comment by BPower0036** [comment]
try https://addons.mozilla.org/nl/firefox/addon/yt-nonstop/

**Comment by ite-klass** [comment]
@BPower0036 causes tracks playing to jump back to the beginning

**Comment by JohnyP36** [comment]
> @BPower0036 causes tracks playing to jump back to the beginning

If you install the extension it reloads the webpage. That's why it starts over again at the beginning of a track.

**Comment by ReemX** [comment]
> try https://addons.mozilla.org/nl/firefox/addon/yt-nonstop/

You are essentially forcing me to switch to firefox which is not ideal in any way the reason I commented here is to try to get the developer of the original extension for chrome to work once more.

**Comment by ite-klass** [comment]
> > @BPower0036 causes tracks playing to jump back to the beginning
> 
> @ite-klass If you install the extension it reloads the webpage. That's why it starts over again at the beginning of a track.

That's not what was happening. It happened three or four times on automatic playback song switches.

**Comment by krystian3w** [comment]
> You are essentially forcing me to switch to firefox which is not ideal

I'm sorry but it's your fault, you omit information that you use Chromium (e.g. Chrome/Edge/Opera) on a daily basis.

For future reference, don't skip this when the repository owner has a break from coding for more than 6 months.

I assume there's a small chance he'll remember his GitHub account.

**Comment by ReemX** [comment]
> > You are essentially forcing me to switch to firefox which is not ideal
> 
> I'm sorry but it's your fault, you omit information that you use Chromium (e.g. Chrome/Edge/Opera) on a daily basis.
> 
> For future reference, don't skip this when the repository owner has a break from coding for more than 6 months:
> 
> ![Screenshot_2023-06-09-09-57-32-719-edit_org mozilla firefox_beta](https://user-images.githubusercontent.com/35370833/244630837-15a1e59d-f114-4f60-9f75-e881c1e14513.jpg) ![Screenshot_2023-06-09-09-58-20-319_org mozilla firefox_beta](https://user-images.githubusercontent.com/35370833/244630870-a94104fc-8776-4f27-8461-aa5ffc1ea72a.jpg)
> 
> I assume there's a small chance he'll remember his GitHub account.
> 
> Both Dutch boys support Edge:
> 
> https://microsoftedge.microsoft.com/addons/detail/youtube-nonstop/ddobgngkifgapahlheghhckckkcgpikf
> 
> https://microsoftedge.microsoft.com/addons/detail/yt-nonstop/ljhaomibkgdhmfdiglflmkijdbiejcom
> 
> Other Chromium needs use CRX viewer (https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin) or manually install from releases:
> 
> https://github.com/JohnyP36/YT-Nonstop/releases
> 
> https://github.com/BPower0036/YT-Nonstop/releases

Thanks the first github link led me to and extention that actually works properly! appreciate it!
